import Head from "next/head";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import requests from "utils/requests";

export const getServerSideProps = async () => {
  const [
    netflixOriginals,
    trending,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((r) => r.json()),
    fetch(requests.fetchTrending).then((r) => r.json()),
    fetch(requests.fetchAction).then((r) => r.json()),
    fetch(requests.fetchComedy).then((r) => r.json()),
    fetch(requests.fetchHorror).then((r) => r.json()),
    fetch(requests.fetchRomance).then((r) => r.json()),
    fetch(requests.fetchDocumentaries).then((r) => r.json()),
  ]);
  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trending: trending.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
    },
  };
};

export default function Home({ netflixOriginals }) {
  console.log(netflixOriginals);

  return (
    <div className="relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511]">
      <Head>
        <title>Home | Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
      </main>
    </div>
  );
}
